# Generated by Django 2.0.2 on 2018-09-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20180830_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Title',
            field=models.CharField(default='title', max_length=200),
        ),
    ]
